apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    zk-name: zk
    component: zk
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    zk-name: zk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
  labels:
    zk-name: zk
    component: zk
spec:
  serviceName: zk-svc
  replicas: 1
  template:
    metadata:
      labels:
        zk-name: zk
        component: zk
    spec:
      containers:
      - name: zk
        imagePullPolicy: IfNotPresent
        image: engapa/zookeeper:3.4.14
        ports:
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name: ZOO_REPLICAS
          value: "1"
        readinessProbe:
          exec:
            command:
            - zk_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - zk_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
